## NumPy 简介
- 功能强大的N维（N-dimensional）数组计算包
- 有用的线性代数，傅里叶变换和随机数功能

### Basic

- ndarray.ndim 数组轴的数
- ndarray.shape sharp(n,m)表示一个n行m列的数组
- ndarray.size 表示array的元素总数
- ndarray.dtype 表示元素的类型，一般来说 numpy.int16, numpy.int32, numpy.float64
- ndarray.itemsize 表示数组中一个元素占用内存的bit大小
- ndarray.data 包含数组实际元素的缓冲区

In [12]:
import numpy as np
a = np.arange(15).reshape(3,5)
print(a) 
print(a.shape)
print(a.size)
print(a.dtype.name)
print(a.itemsize)
print(a.size)
print(type(a))
print(a.data)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
15
int64
8
15
<class 'numpy.ndarray'>


#### 数组的创建

In [17]:
arr_1 = np.array([2,3,4])  #一维数组
print(arr)
print(arr_1.dtype)
arr_2 = np.array([(1.5,2,3), (4,5,6)])
print(arr_2)
print(arr_2.dtype)

[2 3 4]
int64
[[1.5 2.  3. ]
 [4.  5.  6. ]]
float64


> Tip: Array 大小原本是不知道的，但是知道每一个元素的大小，这些最小化了增加阵列的必要性，而且一项昂贵的操作

In [30]:
createZeros = np.zeros((3,4))
print('by zeros' ,createZeros)

createOnes = np.ones((2,3,4),dtype= np.int16)
print('by ones', createOnes)

createRange = np.arange( 10, 30, 5 )
print('by Range',createRange)

by zeros [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
by ones [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
by Range [10 15 20 25]


In [34]:
createRangeFloat = np.arange( 1, 3, 0.5 )
print('by Range',createRangeFloat)   # 通常来说我们并不使用float这个作为步长，使用linspace

createArray = np.linspace(0,2,8)
print('use linspace', createArray)

by Range [1.  1.5 2.  2.5]
use linspace [0.         0.28571429 0.57142857 0.85714286 1.14285714 1.42857143
 1.71428571 2.        ]
